debian/mysql/mysql                usr/share/dbconfig-common/data/typo3-database/install
debian/mysql/4.5.0~alpha3-1       usr/share/dbconfig-common/data/typo3-database/upgrade/mysql
debian/mysql/4.5.0~beta1-1        usr/share/dbconfig-common/data/typo3-database/upgrade/mysql
debian/mysql/4.5.0+dfsg1~beta2    usr/share/dbconfig-common/data/typo3-database/upgrade/mysql
debian/mysql/4.5.0+dfsg1~beta3-1  usr/share/dbconfig-common/data/typo3-database/upgrade/mysql
debian/mysql/4.5.0+dfsg1          usr/share/dbconfig-common/data/typo3-database/upgrade/mysql
