<?php
return array(
	'BE' => array(
		'installToolPassword' => 'bacb98acf97e0b6112b1d1b650b84971',
	),
	'DB' => array(
		'extTablesDefinitionScript' => 'extTables.php',
	),
	'EXT' => array(
		'extListArray' => array(
			'0' => 'info',
			'1' => 'perm',
			'2' => 'func',
			'3' => 'filelist',
			'4' => 'extbase',
			'5' => 'fluid',
			'6' => 'about',
			'7' => 'version',
			'8' => 'tsconfig_help',
			'9' => 'context_help',
			'10' => 'extra_page_cm_options',
			'11' => 'impexp',
			'12' => 'sys_note',
			'13' => 'tstemplate',
			'14' => 'tstemplate_ceditor',
			'15' => 'tstemplate_info',
			'16' => 'tstemplate_objbrowser',
			'17' => 'tstemplate_analyzer',
			'18' => 'func_wizards',
			'19' => 'wizard_crpages',
			'20' => 'wizard_sortpages',
			'21' => 'lowlevel',
			'22' => 'install',
			'23' => 'belog',
			'24' => 'beuser',
			'25' => 'aboutmodules',
			'26' => 'setup',
			'27' => 'taskcenter',
			'28' => 'info_pagetsconfig',
			'29' => 'viewpage',
			'30' => 'rtehtmlarea',
			'31' => 'css_styled_content',
			'32' => 't3skin',
			'33' => 't3editor',
			'34' => 'reports',
			'35' => 'felogin',
			'36' => 'form',
		),
	),
	'SYS' => array(
		'sitename' => 'New TYPO3 site',
	),
);
?>